### ISSUE TITLE
RDM master updated

### ISSUE THREAD

**Issue by Fabio1988** [The-Pokemod-Group/Atlas-All-In-One#1]
https://github.com/The-Pokemod-Group/Atlas-All-In-One/blob/1d3d5dbf41be6d6d990aa06eaab227eb64820de5/README.md?plain=1#L111

RDM master uses now UIcons (merged today from development branch), image generation of 20 GB is not happening anymore.

related PR: https://github.com/RealDeviceMap/RealDeviceMap/pull/285

wiki: https://github.com/RealDeviceMap/RealDeviceMap/wiki/3.-Map-Images

**Comment by esauvisky** [comment]
Glad to see development was merged and official documentation finally updated.

We will update whenever possible or once a PR is submitted.
