### ISSUE TITLE
Update rdm tools to latest version

### ISSUE THREAD

**Issue by Fabio1988** [The-Pokemod-Group/Atlas-All-In-One#10]
You copied content of original rdm tools, pls update folder `tools` or adapt yml to support updates better

**Comment by esauvisky** [comment]
Can you make a PR? Don't have the time to look into this :(

**Comment by Fabio1988** [comment]
I prepared a PR on rdm tools itself.. with that it should be easy to embed in docker :+1: 
https://github.com/PickleRickVE/RealDeviceMap-tools/pull/22

**Comment by Fabio1988** [comment]
> Can you make a PR? Don't have the time to look into this :(

PR ready
