### ISSUE TITLE
Parameter --init-file /data/application/init.sql makes docker-compose fail on a fresh start.

### ISSUE THREAD

**Issue by dynux90** [The-Pokemod-Group/Atlas-All-In-One#11]
https://github.com/The-Pokemod-Group/Atlas-All-In-One/blob/99e66fde3b653f2dc5dfea9da71eb69d9265dfc8/docker-compose.yml#L66

On a fresh start the file /data/application/init.sql does not exists. This leads an aborted atlas-db container creation.

**Comment by esauvisky** [comment]
thanks!
