### ISSUE TITLE
Incorrect Command in Docs

### ISSUE THREAD

**Issue by Jebula999** [The-Pokemod-Group/Atlas-All-In-One#14]
Heya,

There is an incorrect command in the Read-Me.

"Run docker-compose up -d db in your PowerShell from the Atlas-All-In-One folder (Shift+Right click on empty space of the file explorer)"

Should be

"Run docker-compose up -d atlas-db in your PowerShell from the Atlas-All-In-One folder (Shift+Right click on empty space of the file explorer)"

the docker-compose file does not contain "db" but contains "atlas-db"

**Comment by esauvisky** [comment]
Thank you
